services:
  api01:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
    restart: unless-stopped

  api02:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:80'
    deploy:
      resources:
        limits:
          cpus: '0.17'
          memory: '10MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.13'
          memory: '140MB'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
