version: '3.8'

services:
  haproxy:
    image: haproxy:latest
    ports:
      - '9999:9999'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'

  api01:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=db
    ports:
      - '8081:8080'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'

  api02:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=db
    ports:
      - '8082:8080'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
