version: '3.8'

services:
  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8081:8080'
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '200MB'
    restart: unless-stopped

  api02:
    <<: *api
    hostname: api02
    ports:
      - '8082:8080'

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.17'
          memory: '10MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '0.13'
          memory: '140MB'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
